"""
Two-phase pipeline for training a DINOv2-based Value Expert on stitched
3-view videos.

Convention
----------
- Input: a single "video" where each frame is 3 agilex views stitched
  horizontally: [cam_high | cam_left_wrist | cam_right_wrist].  This matches
  the DreamDojo `agilex_3view` output format, so the same model runs on
  real episodes and DreamDojo generations without any format change.
- Per-sample unit = one clip of `num_clip_frames` (default 4) consecutive
  stitched frames + one scalar value label.
- Label convention (consumed by agilex_infer_dinov2_value_switch.py):
    value = 1 - mean(progress in clip)
  so value ~ 0 near task completion, value ~ 1 far from completion.

Data sources
------------
Supported via `pack --source {real, dreamdojo, mixed}`:

  - real       : LeRobot v2.1 dataset with Robometer rewards under
                 <data_dir>/rewards/ (same format as train_switch_head_robometer).
                 3 cam videos (cam_high / cam_left_wrist / cam_right_wrist) are
                 stitched on the fly; labels come from progress_score.
  - dreamdojo  : already-stitched videos generated by DreamDojo
                 (IMAGINAIRE_OUTPUT_ROOT=./outputs_pnp_cup_new_agilex_3view ...).
                 Requires `--dreamdojo_metadata <path>` pointing at a JSON
                 listing entries of the form:
                    {"video": "/abs/path/to/out.mp4",
                     "progress": [0.12, 0.15, ...],   # per decoded frame
                     "task": "pnp_cup",               # optional
                     "source_episode": 5,             # optional
                     "source_frame": 42}              # optional
                 Length of `progress` must match the number of decoded frames
                 (after --extract_fps resampling).
  - mixed      : pack both real and dreamdojo into the same output_dir.
                 The `train` phase simply globs all rollout_*/step_*.npz.

Usage
-----
  # Pack real episodes
  python train_dinov2_value_expert.py pack \
      --source real \
      --data_dir data/pnp_cup_0415_new_agilex \
      --output_dir data/agilex_value_clips_pnp_cup_0416

  # Pack DreamDojo generations (requires metadata json)
  python train_dinov2_value_expert.py pack \
      --source dreamdojo \
      --dreamdojo_metadata data/dreamdojo_progress_0416.json \
      --output_dir data/agilex_value_clips_pnp_cup_0416

  # Pack both at once
  python train_dinov2_value_expert.py pack \
      --source mixed \
      --data_dir data/pnp_cup_0415_new_agilex \
      --dreamdojo_metadata data/dreamdojo_progress_0416.json \
      --output_dir data/agilex_value_clips_pnp_cup_0416

  # Train
  torchrun --nproc_per_node=8 train_dinov2_value_expert.py train \
      --data_dir data/agilex_value_clips_pnp_cup_0416 \
      --val_ratio 0.1 \
      --output_dir checkpoints/dinov2_value_expert \
      --wandb_project value_expert --wandb_run_name value_expert_0416
"""

import argparse
import glob
import json
import logging
import os
import pathlib
import random
import time

import av
import numpy as np
import torch
import torch.distributed as dist
import torch.nn as nn
import torch.nn.functional as F
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.utils.data import DataLoader, Dataset
from torch.utils.data.distributed import DistributedSampler

try:
    import wandb
except ImportError:
    wandb = None


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
REAL_CAMERAS = ["cam_high", "cam_left_wrist", "cam_right_wrist"]
DEFAULT_SAVE_H = 224
DEFAULT_SAVE_W = 672   # 14 * 48; 3x save_h for 1:3 stitched aspect


# ============================================================================
#  Model: DINOv2ValueExpert
# ============================================================================

class DINOv2ValueExpert(nn.Module):
    """
    Per-clip scalar value regressor.

      DINOv2 (frozen) per-frame features
        → temporal TransformerEncoder over L clip frames
        → mean-pool → MLP head → scalar value

    forward(video): video is (B, L, 3, H, W) uint-normalized floats in [0,1]
    score_video(video, window_size, stride): slide window over a longer video
    """

    def __init__(
        self,
        num_clip_frames: int = 4,
        dinov2_model: str = "dinov2_vitb14",
        attn_heads: int = 8,
        attn_layers: int = 2,
        hidden_dim: int = 512,
        freeze_backbone: bool = True,
        dropout: float = 0.1,
    ):
        super().__init__()
        self.num_clip_frames = num_clip_frames

        self.backbone = torch.hub.load("facebookresearch/dinov2", dinov2_model)
        self.feature_dim = self.backbone.embed_dim
        self.freeze_backbone = freeze_backbone
        if freeze_backbone:
            for p in self.backbone.parameters():
                p.requires_grad = False
            self.backbone.eval()

        self.register_buffer(
            "img_mean", torch.tensor([0.485, 0.456, 0.406]).view(1, 3, 1, 1)
        )
        self.register_buffer(
            "img_std", torch.tensor([0.229, 0.224, 0.225]).view(1, 3, 1, 1)
        )

        # Up to num_clip_frames learnable temporal positions. score_video always
        # passes exactly num_clip_frames per window, so this is the tight size.
        self.temporal_pos_emb = nn.Parameter(
            torch.zeros(num_clip_frames, self.feature_dim)
        )
        nn.init.trunc_normal_(self.temporal_pos_emb, std=0.02)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=self.feature_dim,
            nhead=attn_heads,
            dim_feedforward=self.feature_dim * 4,
            dropout=dropout,
            activation="gelu",
            batch_first=True,
            norm_first=True,
        )
        self.temporal_attn = nn.TransformerEncoder(encoder_layer, num_layers=attn_layers)

        self.head = nn.Sequential(
            nn.LayerNorm(self.feature_dim),
            nn.Linear(self.feature_dim, hidden_dim),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, 1),
        )

        # Input resolution target for DINOv2 (divisible by 14). Matches
        # stitched 3-view save size by default.
        self.resize_h = DEFAULT_SAVE_H
        self.resize_w = DEFAULT_SAVE_W

    def set_input_resolution(self, h: int, w: int):
        assert h % 14 == 0 and w % 14 == 0, "DINOv2 input dims must be multiples of 14"
        self.resize_h = h
        self.resize_w = w

    def _encode_frames(self, flat_imgs: torch.Tensor) -> torch.Tensor:
        """(N, 3, H, W) float in [0,1] → (N, feature_dim)."""
        flat = F.interpolate(
            flat_imgs, size=(self.resize_h, self.resize_w),
            mode="bilinear", align_corners=False,
        )
        flat = (flat - self.img_mean) / self.img_std
        if self.freeze_backbone:
            with torch.no_grad():
                feats = self.backbone(flat)
        else:
            feats = self.backbone(flat)
        return feats

    def forward(self, video: torch.Tensor) -> torch.Tensor:
        """video: (B, L, 3, H, W) → (B,) scalar value per clip."""
        B, L, C, H, W = video.shape
        if L > self.num_clip_frames:
            raise ValueError(
                f"Clip length {L} exceeds num_clip_frames={self.num_clip_frames}"
            )
        feats = self._encode_frames(video.reshape(B * L, C, H, W))
        feats = feats.reshape(B, L, -1)
        feats = feats + self.temporal_pos_emb[:L].unsqueeze(0)
        feats = self.temporal_attn(feats)
        pooled = feats.mean(dim=1)
        return self.head(pooled).squeeze(-1)

    @torch.no_grad()
    def score_video(
        self, video: torch.Tensor, window_size: int = 4, stride: int = 1,
    ) -> torch.Tensor:
        """(B, L, 3, H, W) video → (B, num_windows) values."""
        B, L = video.shape[0], video.shape[1]
        if L < window_size:
            pad = video[:, -1:].expand(B, window_size - L, -1, -1, -1)
            video = torch.cat([video, pad], dim=1)
            L = window_size
        scores = []
        for start in range(0, L - window_size + 1, stride):
            w = video[:, start : start + window_size]
            scores.append(self.forward(w))
        return torch.stack(scores, dim=1)


# ============================================================================
#  Video decoding + stitching
# ============================================================================

def extract_frames_pyav(
    video_path: str, fps: float = 5.0, max_frames: int = 1024,
) -> np.ndarray:
    """Decode video with PyAV (AV1-compatible). Returns uint8 (T, H, W, 3)."""
    container = av.open(video_path)
    stream = container.streams.video[0]
    video_fps = float(stream.average_rate)
    frame_interval = max(1, int(round(video_fps / fps)))

    frames = []
    for i, frame in enumerate(container.decode(video=0)):
        if i % frame_interval == 0:
            frames.append(frame.to_ndarray(format="rgb24"))
            if len(frames) >= max_frames:
                break
    container.close()

    if not frames:
        return np.array([], dtype=np.uint8)
    return np.stack(frames, axis=0)


def stitch_3view(
    top: np.ndarray, left: np.ndarray, right: np.ndarray,
    layout: str = "top_left_right",
    target_h: int = DEFAULT_SAVE_H, target_w_per_view: int | None = None,
) -> np.ndarray:
    """Horizontally concatenate 3 camera frames into one stitched frame.

    Each of top/left/right is (T, H, W, 3). Heights are resized to target_h;
    widths are set to target_w_per_view (if provided) or the per-view width
    needed for a final width of DEFAULT_SAVE_W. Returns (T, target_h, 3*target_w_per_view, 3) uint8.
    """
    from PIL import Image

    if target_w_per_view is None:
        target_w_per_view = DEFAULT_SAVE_W // 3

    views = {"top": top, "left": left, "right": right}
    order = {
        "top_left_right": ["top", "left", "right"],
        "top_right_left": ["top", "right", "left"],
        "left_top_right": ["left", "top", "right"],
    }[layout]

    T = min(v.shape[0] for v in views.values())
    out = np.zeros((T, target_h, target_w_per_view * 3, 3), dtype=np.uint8)
    for t in range(T):
        stitched = np.zeros((target_h, target_w_per_view * 3, 3), dtype=np.uint8)
        for col, key in enumerate(order):
            im = Image.fromarray(views[key][t])
            im = im.resize((target_w_per_view, target_h), Image.BILINEAR)
            stitched[:, col * target_w_per_view : (col + 1) * target_w_per_view] = (
                np.asarray(im)
            )
        out[t] = stitched
    return out


def resize_stitched(frames: np.ndarray, h: int, w: int) -> np.ndarray:
    """Resize pre-stitched (T, H, W, 3) to (T, h, w, 3)."""
    from PIL import Image
    T = frames.shape[0]
    out = np.zeros((T, h, w, 3), dtype=np.uint8)
    for t in range(T):
        im = Image.fromarray(frames[t]).resize((w, h), Image.BILINEAR)
        out[t] = np.asarray(im)
    return out


# ============================================================================
#  LeRobot v2.1 helpers (real source)
# ============================================================================

def _load_dataset_info(data_dir: pathlib.Path) -> dict:
    with open(data_dir / "meta" / "info.json") as f:
        return json.load(f)


def _load_task(data_dir: pathlib.Path) -> str:
    with open(data_dir / "meta" / "tasks.jsonl") as f:
        return json.loads(f.readline().strip())["task"]


def _get_video_path(data_dir: pathlib.Path, episode_index: int, camera: str) -> pathlib.Path:
    video_key = f"observation.images.{camera}"
    return (
        data_dir / "videos" / "chunk-000" / video_key
        / f"episode_{episode_index:06d}.mp4"
    )


# ============================================================================
#  Windowing + labeling
# ============================================================================

def _make_windows(
    stitched: np.ndarray, progress: np.ndarray,
    num_clip_frames: int, stride: int,
) -> list[dict]:
    """Slide window over a stitched (T, H, W, 3) video with aligned progress."""
    T = min(stitched.shape[0], len(progress))
    records = []
    for start in range(0, T - num_clip_frames + 1, stride):
        end = start + num_clip_frames
        clip = stitched[start:end]                          # (L, H, W, 3)
        clip_progress = progress[start:end]
        value = float(1.0 - np.mean(clip_progress))
        records.append({
            "start": start,
            "end": end,
            "frames": clip,
            "value": value,
            "mean_progress": float(np.mean(clip_progress)),
        })
    return records


def _write_window_npz(
    out_dir: pathlib.Path, step_i: int, rec: dict, meta: dict,
):
    out_dir.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        out_dir / f"step_{step_i:05d}.npz",
        frames=rec["frames"],
        value=np.float32(rec["value"]),
        mean_progress=np.float32(rec["mean_progress"]),
        start=np.int32(rec["start"]),
        end=np.int32(rec["end"]),
        **{k: np.array(v) for k, v in meta.items()},
    )


# ============================================================================
#  Phase 1: pack
# ============================================================================

def _pack_real(args, output_dir: pathlib.Path, stats: dict):
    data_dir = pathlib.Path(args.data_dir)
    rewards_dir = pathlib.Path(args.rewards_dir) if args.rewards_dir else data_dir / "rewards"

    info = _load_dataset_info(data_dir)
    task = _load_task(data_dir)

    available_eps = sorted({
        int(f.stem.split("_")[1]) for f in rewards_dir.glob("episode_*_progress.npy")
    })
    if args.episodes:
        ep_start, ep_end = map(int, args.episodes.split(":"))
        available_eps = [e for e in available_eps if ep_start <= e < ep_end]

    logging.info(f"[real] Dataset: {data_dir}")
    logging.info(f"[real] Rewards: {rewards_dir}")
    logging.info(f"[real] Task: {task}")
    logging.info(f"[real] Episodes with rewards: {len(available_eps)}")

    task_segment = task.replace(" ", "_")[:50]
    t_start = time.time()

    for ep_idx in available_eps:
        rollout_id = f"rollout_{task_segment}_real_ep{ep_idx}_done"
        rollout_dir = output_dir / rollout_id
        if rollout_dir.exists() and not args.overwrite:
            logging.info(f"  [real] skip ep {ep_idx} (already packed)")
            continue

        progress_path = rewards_dir / f"episode_{ep_idx:06d}_progress.npy"
        progress_array = np.load(str(progress_path)).astype(np.float32)

        # Decode 3 cams at extract_fps
        cam_frames = {}
        for cam in REAL_CAMERAS:
            vp = _get_video_path(data_dir, ep_idx, cam)
            if not vp.exists():
                logging.warning(f"  [real] ep {ep_idx}: missing {cam}, skip")
                break
            frames = extract_frames_pyav(str(vp), fps=args.extract_fps,
                                         max_frames=args.max_frames)
            if frames.size == 0:
                logging.warning(f"  [real] ep {ep_idx}: failed to decode {cam}, skip")
                break
            cam_frames[cam] = frames
        if len(cam_frames) != len(REAL_CAMERAS):
            continue

        # Align to shortest length
        T_cam = min(f.shape[0] for f in cam_frames.values())
        for cam in cam_frames:
            cam_frames[cam] = cam_frames[cam][:T_cam]

        # Subsample progress to match extract_fps
        dataset_fps = info["fps"]
        stride = max(1, int(round(dataset_fps / args.extract_fps)))
        progress_sub = progress_array[::stride][:T_cam]
        T = min(T_cam, len(progress_sub))
        for cam in cam_frames:
            cam_frames[cam] = cam_frames[cam][:T]
        progress_sub = progress_sub[:T]

        # Stitch
        stitched = stitch_3view(
            cam_frames["cam_high"], cam_frames["cam_left_wrist"], cam_frames["cam_right_wrist"],
            layout=args.view_layout,
            target_h=args.save_h, target_w_per_view=args.save_w // 3,
        )

        # Window & save
        windows = _make_windows(
            stitched, progress_sub,
            num_clip_frames=args.num_clip_frames, stride=args.window_stride,
        )
        if not windows:
            logging.warning(f"  [real] ep {ep_idx}: no windows, skip")
            continue

        for step_i, rec in enumerate(windows):
            _write_window_npz(rollout_dir, step_i, rec, meta={
                "source": "real",
                "task": task,
                "episode_idx": ep_idx,
            })

        stats["real_rollouts"] += 1
        stats["real_clips"] += len(windows)
        elapsed = time.time() - t_start
        logging.info(
            f"  [real] ep {ep_idx}: {len(windows)} clips, "
            f"mean_value={np.mean([r['value'] for r in windows]):.3f} "
            f"(progress=[{progress_sub.min():.3f}, {progress_sub.max():.3f}]) "
            f"| elapsed {elapsed:.0f}s"
        )


def _pack_dreamdojo(args, output_dir: pathlib.Path, stats: dict):
    if not args.dreamdojo_metadata:
        raise ValueError("--dreamdojo_metadata is required for source=dreamdojo/mixed")
    meta_path = pathlib.Path(args.dreamdojo_metadata)
    with open(meta_path) as f:
        meta_json = json.load(f)
    entries = meta_json["entries"] if isinstance(meta_json, dict) else meta_json

    logging.info(f"[dd] Metadata: {meta_path}")
    logging.info(f"[dd] Entries: {len(entries)}")

    t_start = time.time()
    for ent_i, ent in enumerate(entries):
        video_path = ent["video"]
        progress = np.asarray(ent["progress"], dtype=np.float32)
        task = ent.get("task", "dreamdojo")
        src_ep = ent.get("source_episode", -1)
        src_frame = ent.get("source_frame", -1)

        task_segment = task.replace(" ", "_")[:50]
        basename = pathlib.Path(video_path).stem
        rollout_id = f"rollout_{task_segment}_dd_{basename}_done"
        rollout_dir = output_dir / rollout_id
        if rollout_dir.exists() and not args.overwrite:
            logging.info(f"  [dd] skip {basename} (already packed)")
            continue

        if not os.path.exists(video_path):
            logging.warning(f"  [dd] missing video: {video_path}, skip")
            continue

        stitched_raw = extract_frames_pyav(
            video_path, fps=args.extract_fps, max_frames=args.max_frames,
        )
        if stitched_raw.size == 0:
            logging.warning(f"  [dd] failed to decode: {video_path}, skip")
            continue

        # Resize stitched frames to save size (preserves 1:3 aspect if source is 1:3).
        stitched = resize_stitched(stitched_raw, args.save_h, args.save_w)

        T = min(stitched.shape[0], len(progress))
        stitched = stitched[:T]
        progress = progress[:T]

        if T < args.num_clip_frames:
            logging.warning(
                f"  [dd] {basename}: only {T} frames, need {args.num_clip_frames}, skip"
            )
            continue

        windows = _make_windows(
            stitched, progress,
            num_clip_frames=args.num_clip_frames, stride=args.window_stride,
        )
        if not windows:
            continue

        for step_i, rec in enumerate(windows):
            _write_window_npz(rollout_dir, step_i, rec, meta={
                "source": "dreamdojo",
                "task": task,
                "source_episode": src_ep,
                "source_frame": src_frame,
                "video": video_path,
            })

        stats["dd_rollouts"] += 1
        stats["dd_clips"] += len(windows)
        elapsed = time.time() - t_start
        logging.info(
            f"  [dd] {basename}: {len(windows)} clips, "
            f"mean_value={np.mean([r['value'] for r in windows]):.3f} "
            f"(progress=[{progress.min():.3f}, {progress.max():.3f}]) "
            f"| ({ent_i + 1}/{len(entries)}) elapsed {elapsed:.0f}s"
        )


def pack(args):
    output_dir = pathlib.Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    stats = {"real_rollouts": 0, "real_clips": 0, "dd_rollouts": 0, "dd_clips": 0}

    if args.source in ("real", "mixed"):
        if not args.data_dir:
            raise ValueError("--data_dir is required for source=real/mixed")
        _pack_real(args, output_dir, stats)

    if args.source in ("dreamdojo", "mixed"):
        _pack_dreamdojo(args, output_dir, stats)

    meta_path = output_dir / "value_clips_meta.json"
    with open(meta_path, "w") as f:
        json.dump({
            "source": args.source,
            "num_clip_frames": args.num_clip_frames,
            "window_stride": args.window_stride,
            "save_h": args.save_h,
            "save_w": args.save_w,
            "view_layout": args.view_layout,
            "stats": stats,
        }, f, indent=2)

    logging.info(f"\nPacking complete.")
    logging.info(f"  Real:      {stats['real_rollouts']} rollouts, {stats['real_clips']} clips")
    logging.info(f"  DreamDojo: {stats['dd_rollouts']} rollouts, {stats['dd_clips']} clips")
    logging.info(f"  Saved to:  {output_dir}")


# ============================================================================
#  Phase 2: train
# ============================================================================

class ValueClipDataset(Dataset):
    def __init__(self, data_dir: str, files: list[str] | None = None):
        if files is not None:
            self.files = sorted(files)
        else:
            self.files = sorted(glob.glob(
                os.path.join(data_dir, "rollout_*", "step_*.npz")
            ))
        if not self.files:
            raise FileNotFoundError(f"No value-clip npz files found in {data_dir}")
        first = np.load(self.files[0], allow_pickle=True)
        self.num_clip_frames, self.h, self.w, _ = first["frames"].shape
        logging.info(
            f"ValueClipDataset: {len(self.files)} clips, "
            f"shape=({self.num_clip_frames}, {self.h}, {self.w}, 3)"
        )

    def __len__(self):
        return len(self.files)

    def __getitem__(self, idx):
        data = np.load(self.files[idx], allow_pickle=True)
        frames = data["frames"]                                # (L, H, W, 3) uint8
        video = torch.from_numpy(frames.copy()).permute(0, 3, 1, 2).float() / 255.0
        value = torch.tensor(float(data["value"]), dtype=torch.float32)
        return video, value


def _split_by_rollout(
    data_dir: str, val_ratio: float, seed: int,
) -> tuple[ValueClipDataset, ValueClipDataset]:
    files = sorted(glob.glob(os.path.join(data_dir, "rollout_*", "step_*.npz")))
    if not files:
        raise FileNotFoundError(f"No value-clip npz files found in {data_dir}")
    rollouts: dict[str, list[str]] = {}
    for f in files:
        rid = os.path.basename(os.path.dirname(f))
        rollouts.setdefault(rid, []).append(f)
    rollout_ids = sorted(rollouts.keys())
    rng = random.Random(seed)
    shuffled = rollout_ids[:]
    rng.shuffle(shuffled)
    n_val = max(1, int(round(len(shuffled) * val_ratio)))
    if n_val >= len(shuffled):
        raise ValueError(f"val_ratio={val_ratio} leaves no train rollouts")
    val_ids = set(shuffled[:n_val])
    train_files = [f for r in rollout_ids if r not in val_ids for f in rollouts[r]]
    val_files = [f for r in rollout_ids if r in val_ids for f in rollouts[r]]
    logging.info(
        f"Split by rollout (seed={seed}): "
        f"{len(rollout_ids) - n_val} train / {n_val} val rollouts "
        f"({len(train_files)} / {len(val_files)} clips)"
    )
    return (
        ValueClipDataset(data_dir, files=train_files),
        ValueClipDataset(data_dir, files=val_files),
    )


def _collate_value(batch):
    videos, values = zip(*batch)
    return torch.stack(videos), torch.stack(values)


def _setup_distributed():
    if "RANK" not in os.environ:
        return 0, 0, 1
    dist.init_process_group(backend="nccl")
    rank = dist.get_rank()
    local_rank = int(os.environ.get("LOCAL_RANK", 0))
    world_size = dist.get_world_size()
    torch.cuda.set_device(local_rank)
    return rank, local_rank, world_size


def _cleanup_distributed():
    if dist.is_initialized():
        dist.destroy_process_group()


def train(args):
    rank, local_rank, world_size = _setup_distributed()
    distributed = world_size > 1
    is_main = rank == 0
    device = torch.device(f"cuda:{local_rank}" if torch.cuda.is_available() else "cpu")
    if is_main:
        logging.info(f"Using device: {device}  (world_size={world_size})")

    if args.val_dir:
        train_dataset = ValueClipDataset(args.data_dir)
        val_dataset = ValueClipDataset(args.val_dir)
    elif args.val_ratio > 0:
        train_dataset, val_dataset = _split_by_rollout(
            args.data_dir, val_ratio=args.val_ratio, seed=args.val_split_seed,
        )
    else:
        train_dataset = ValueClipDataset(args.data_dir)
        val_dataset = None

    model = DINOv2ValueExpert(
        num_clip_frames=args.num_clip_frames,
        dinov2_model=args.dinov2_model,
        attn_heads=args.attn_heads,
        attn_layers=args.attn_layers,
        hidden_dim=args.hidden_dim,
        freeze_backbone=args.freeze_backbone,
        dropout=args.dropout,
    ).to(device)
    model.set_input_resolution(train_dataset.h, train_dataset.w)

    if distributed:
        model = DDP(model, device_ids=[local_rank], output_device=local_rank,
                    find_unused_parameters=False)
    raw_model = model.module if distributed else model

    train_sampler = DistributedSampler(train_dataset, shuffle=True) if distributed else None
    train_loader = DataLoader(
        train_dataset, batch_size=args.batch_size,
        shuffle=(train_sampler is None), sampler=train_sampler,
        num_workers=args.num_workers, pin_memory=True,
        collate_fn=_collate_value,
    )
    val_sampler = DistributedSampler(val_dataset, shuffle=False) if (distributed and val_dataset) else None
    val_loader = (
        DataLoader(
            val_dataset, batch_size=args.batch_size,
            shuffle=False, sampler=val_sampler,
            num_workers=args.num_workers, pin_memory=True,
            collate_fn=_collate_value,
        )
        if val_dataset else None
    )

    trainable = [p for p in model.parameters() if p.requires_grad]
    if is_main:
        logging.info(f"Trainable parameters: {sum(p.numel() for p in trainable):,}")

    optimizer = torch.optim.AdamW(trainable, lr=args.lr, weight_decay=args.weight_decay)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=args.epochs)
    criterion = nn.MSELoss()

    output_dir = pathlib.Path(args.output_dir)
    if is_main:
        output_dir.mkdir(parents=True, exist_ok=True)
    if distributed:
        dist.barrier()

    best_val_mse = float("inf")

    use_wandb = is_main and wandb is not None and args.wandb_project
    if use_wandb:
        wandb.init(
            project=args.wandb_project,
            name=args.wandb_run_name,
            config={
                "dinov2_model": args.dinov2_model,
                "num_clip_frames": args.num_clip_frames,
                "attn_heads": args.attn_heads,
                "attn_layers": args.attn_layers,
                "hidden_dim": args.hidden_dim,
                "freeze_backbone": args.freeze_backbone,
                "dropout": args.dropout,
                "batch_size": args.batch_size,
                "lr": args.lr,
                "weight_decay": args.weight_decay,
                "epochs": args.epochs,
                "world_size": world_size,
                "data_dir": args.data_dir,
                "num_train_clips": len(train_dataset),
                "input_resolution": [train_dataset.h, train_dataset.w],
            },
        )

    for epoch in range(args.epochs):
        if train_sampler is not None:
            train_sampler.set_epoch(epoch)

        model.train()
        if args.freeze_backbone:
            raw_model.backbone.eval()

        total_loss, n_batches = 0.0, 0
        total_abs_err, total_count = 0.0, 0

        for video, value in train_loader:
            video = video.to(device, non_blocking=True)
            value = value.to(device, non_blocking=True)
            pred = model(video)
            loss = criterion(pred, value)

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(trainable, 1.0)
            optimizer.step()

            total_loss += loss.item()
            n_batches += 1
            total_abs_err += (pred - value).abs().sum().item()
            total_count += value.numel()

        avg_train_loss = total_loss / max(n_batches, 1)
        avg_train_mae = total_abs_err / max(total_count, 1)
        scheduler.step()

        val_str = "N/A"
        avg_val_loss = None
        if val_loader is not None:
            model.eval()
            vl, vn = 0.0, 0
            vabs, vcount = 0.0, 0
            with torch.no_grad():
                for video, value in val_loader:
                    video = video.to(device, non_blocking=True)
                    value = value.to(device, non_blocking=True)
                    pred = model(video)
                    vl += criterion(pred, value).item()
                    vn += 1
                    vabs += (pred - value).abs().sum().item()
                    vcount += value.numel()
            avg_val_loss = vl / max(vn, 1)
            avg_val_mae = vabs / max(vcount, 1)
            val_str = f"mse={avg_val_loss:.4f} mae={avg_val_mae:.4f}"

            if is_main and avg_val_loss < best_val_mse:
                best_val_mse = avg_val_loss
                torch.save(raw_model.state_dict(), output_dir / "best_model.pt")
                logging.info(f"  -> Saved best model (val_mse={avg_val_loss:.4f})")

        if is_main:
            logging.info(
                f"Epoch {epoch + 1}/{args.epochs}  "
                f"train_mse={avg_train_loss:.4f} train_mae={avg_train_mae:.4f}  "
                f"val=[{val_str}]  lr={scheduler.get_last_lr()[0]:.2e}"
            )

        if use_wandb:
            log = {
                "epoch": epoch + 1,
                "train/mse": avg_train_loss,
                "train/mae": avg_train_mae,
                "lr": scheduler.get_last_lr()[0],
            }
            if val_loader is not None:
                log["val/mse"] = avg_val_loss
                log["val/mae"] = avg_val_mae
            wandb.log(log, step=epoch + 1)

        if is_main and (epoch + 1) % args.save_every == 0:
            torch.save(raw_model.state_dict(), output_dir / f"model_epoch{epoch + 1}.pt")

    if is_main:
        torch.save(raw_model.state_dict(), output_dir / "model_final.pt")
        logging.info(f"Training complete. Models saved to {output_dir}")

    if use_wandb:
        wandb.finish()
    _cleanup_distributed()


# ============================================================================
#  CLI
# ============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Train DINOv2 Value Expert on stitched 3-view video clips."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # ---- pack ----
    p_pack = subparsers.add_parser(
        "pack", help="Pack real LeRobot / DreamDojo videos into per-clip npz files"
    )
    p_pack.add_argument(
        "--source", type=str, choices=["real", "dreamdojo", "mixed"], required=True,
    )
    p_pack.add_argument("--data_dir", type=str, default=None,
                        help="LeRobot v2.1 dataset dir (required for real/mixed)")
    p_pack.add_argument("--rewards_dir", type=str, default=None,
                        help="Robometer rewards dir (default: <data_dir>/rewards)")
    p_pack.add_argument("--dreamdojo_metadata", type=str, default=None,
                        help="Metadata JSON for DreamDojo videos "
                             "(required for dreamdojo/mixed)")
    p_pack.add_argument("--output_dir", type=str, required=True)
    p_pack.add_argument("--episodes", type=str, default=None,
                        help="Episode range for real source, e.g. '0:50'")
    p_pack.add_argument("--extract_fps", type=float, default=5.0,
                        help="FPS to decode videos at; progress array is subsampled to match")
    p_pack.add_argument("--max_frames", type=int, default=1024)
    p_pack.add_argument("--num_clip_frames", type=int, default=4)
    p_pack.add_argument("--window_stride", type=int, default=1,
                        help="Stride between clip starts (in extracted frames)")
    p_pack.add_argument("--save_h", type=int, default=DEFAULT_SAVE_H,
                        help="Height of saved stitched frame (must be divisible by 14)")
    p_pack.add_argument("--save_w", type=int, default=DEFAULT_SAVE_W,
                        help="Total width of saved stitched frame "
                             "(must be divisible by 14 and by 3)")
    p_pack.add_argument("--view_layout", type=str, default="top_left_right",
                        choices=["top_left_right", "top_right_left", "left_top_right"],
                        help="Order of 3-view horizontal concat (real source only)")
    p_pack.add_argument("--overwrite", action="store_true",
                        help="Repack even if rollout dir already exists")

    # ---- train ----
    p_train = subparsers.add_parser(
        "train", help="Train DINOv2ValueExpert on packed clips"
    )
    p_train.add_argument("--data_dir", type=str, required=True)
    p_train.add_argument("--val_dir", type=str, default=None)
    p_train.add_argument("--val_ratio", type=float, default=0.0)
    p_train.add_argument("--val_split_seed", type=int, default=42)
    p_train.add_argument("--output_dir", type=str,
                         default="checkpoints/dinov2_value_expert")
    p_train.add_argument("--dinov2_model", type=str, default="dinov2_vitb14",
                         choices=["dinov2_vits14", "dinov2_vitb14",
                                  "dinov2_vitl14", "dinov2_vitg14"])
    p_train.add_argument("--num_clip_frames", type=int, default=4)
    p_train.add_argument("--attn_heads", type=int, default=8)
    p_train.add_argument("--attn_layers", type=int, default=2)
    p_train.add_argument("--hidden_dim", type=int, default=512)
    p_train.add_argument("--dropout", type=float, default=0.1)
    p_train.add_argument("--freeze_backbone", action="store_true", default=True)
    p_train.add_argument("--no_freeze_backbone", dest="freeze_backbone",
                         action="store_false")
    p_train.add_argument("--batch_size", type=int, default=32)
    p_train.add_argument("--lr", type=float, default=1e-4)
    p_train.add_argument("--weight_decay", type=float, default=1e-4)
    p_train.add_argument("--epochs", type=int, default=20)
    p_train.add_argument("--num_workers", type=int, default=4)
    p_train.add_argument("--save_every", type=int, default=1)
    p_train.add_argument("--wandb_project", type=str, default=None)
    p_train.add_argument("--wandb_run_name", type=str, default=None)

    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
    )

    if args.command == "pack":
        if args.save_h % 14 != 0 or args.save_w % 14 != 0:
            raise ValueError("save_h and save_w must be divisible by 14 (DINOv2 patch size)")
        if args.save_w % 3 != 0:
            raise ValueError("save_w must be divisible by 3 (3-view stitch)")
        pack(args)
    elif args.command == "train":
        train(args)


if __name__ == "__main__":
    main()
