"""Fully-offline RLT training — RL Token + Actor-Critic, all from offline data.

No simulator, no server, no online rollouts. One command does everything:
  1. Train the RL Token encoder-decoder (representation learning via
     autoregressive reconstruction of frozen VLA prefix embeddings).
  2. Train the Actor-Critic via offline TD3 using the learned z_rl.

Reads Parquet + MP4 data from a local directory
(e.g. data/libero/vlaw_synthetic).

Supports two data layouts:
  * VLAW synthetic (generate_vlaw_synthetic_data.py) — MP4 videos + flat parquet
  * Perturbed trajectories — embedded PNG images in parquet

Usage:
  python scripts/train_rlt_offline.py \
      --base_config pi05_libero \
      --base_checkpoint gs://openpi-assets/checkpoints/pi05_libero \
      --data_dir data/libero/vlaw_synthetic \
      --output_dir checkpoints/rlt_libero_10/offline \
      --rl_token_steps 5000 \
      --rl_steps 20000
"""

import collections
import dataclasses
import io
import json
import logging
import math
import pathlib
import time
from typing import Any

import numpy as np
import tyro

logger = logging.getLogger("rlt_offline")


@dataclasses.dataclass
class Args:
    """Fully-offline RLT training arguments."""

    base_config: str = "pi05_libero"
    base_checkpoint: str = "gs://openpi-assets/checkpoints/pi05_libero"
    task_suite_name: str = "libero_10"

    data_dir: str = "data/libero/vlaw_synthetic"
    # If True, treat *all* episodes as successful (reward=1).
    assume_success: bool = True

    rl_token_dim: int = 2048
    encoder_num_layers: int = 2
    decoder_num_layers: int = 2
    actor_hidden_dim: int = 256
    actor_num_layers: int = 2
    critic_hidden_dim: int = 256
    critic_num_layers: int = 2
    rl_chunk_length: int = 10
    actor_std: float = 0.1
    ref_action_dropout: float = 0.5

    rl_token_steps: int = 5000
    rl_token_lr: float = 1e-4
    rl_token_batch_size: int = 32
    # Also fine-tune VLA backbone during RL token training.
    finetune_vla: bool = True
    vla_finetune_weight: float = 0.1

    rl_steps: int = 20000
    rl_batch_size: int = 256
    actor_lr: float = 3e-4
    critic_lr: float = 3e-4
    bc_regularizer_beta: float = 1.0
    discount_gamma: float = 0.99
    target_network_tau: float = 0.005
    critic_updates_per_actor: int = 2
    vla_num_steps: int = 10
    # Also fine-tune VLA backbone during Phase 2 (offline TD3).
    finetune_vla_phase2: bool = False
    vla_lr_phase2: float = 1e-5
    vla_phase2_weight: float = 0.1
    # How often (in TD3 steps) to perform a VLA fine-tune step.
    vla_phase2_interval: int = 1

    seed: int = 42
    output_dir: str = "checkpoints/rlt_{task}/offline"
    log_interval: int = 100
    save_interval: int = 2000
    resize_size: int = 224

    def __post_init__(self):
        task = self.task_suite_name
        for f in dataclasses.fields(self):
            val = getattr(self, f.name)
            if isinstance(val, str) and "{task}" in val:
                object.__setattr__(self, f.name, val.replace("{task}", task))


class OfflineDataset:
    """Load VLAW-synthetic or perturbed-traj episodes into RAM for offline RL.

    Supports two data layouts:

    **VLAW synthetic** (generated by generate_vlaw_synthetic_data.py):
      - Parquet columns: ``observation.state``, ``action``, ``success``,
        ``next.done``, ``task_index``, ...
      - Images stored as MP4 videos under
        ``videos/chunk-XXX/observation.images.agentview/episode_XXXXXX.mp4``

    **Perturbed trajectories** (collected by the LIBERO perturbation pipeline):
      - Parquet columns: ``state``, ``actions`` (note plural), embedded PNG
        ``image`` / ``wrist_image`` struct columns.

    Each sampled element is a transition dict:
        image, wrist_image          : uint8 (resize_size, resize_size, 3)
        state                       : float32 (8,)
        action_chunk                : float32 (C, action_dim)  — raw 7-dim
        reward, done                : float32 (1,)
        next_image, next_wrist_image: uint8 (resize_size, resize_size, 3)
        next_state                  : float32 (8,)
        task_description            : str
    """

    def __init__(
        self,
        data_dir: str | pathlib.Path,
        chunk_length: int = 10,
        assume_success: bool = True,
        resize_size: int = 224,
    ):
        data_dir = pathlib.Path(data_dir)
        self.chunk_length = chunk_length
        self.resize_size = resize_size
        self.transitions: list[dict[str, Any]] = []

        # Decide which layout we're dealing with
        videos_dir = data_dir / "videos"
        self._is_vlaw = videos_dir.exists()

        if self._is_vlaw:
            self._load_vlaw(data_dir, assume_success)
        else:
            self._load_perturbed(data_dir, assume_success)

        logger.info(f"Total transitions loaded: {len(self.transitions)}")

    # ------------------------------------------------------------------ #
    # VLAW synthetic layout (MP4 videos + flat parquet columns)
    # ------------------------------------------------------------------ #

    def _load_vlaw(self, data_dir: pathlib.Path, assume_success: bool):
        import pyarrow.parquet as pq

        logger.info(f"Detected VLAW synthetic layout in {data_dir}")

        parquet_files = sorted((data_dir / "data").rglob("*.parquet"))
        if not parquet_files:
            raise FileNotFoundError(f"No parquet files under {data_dir / 'data'}")
        logger.info(f"Found {len(parquet_files)} parquet files")

        # Load task descriptions
        task_map: dict[int, str] = {}
        tasks_jsonl = data_dir / "meta" / "tasks.jsonl"
        if tasks_jsonl.exists():
            for line in tasks_jsonl.read_text().splitlines():
                obj = json.loads(line)
                task_map[obj["task_index"]] = obj["task"]

        # Per-episode metadata
        episodes_meta: dict[int, dict] = {}
        episodes_jsonl = data_dir / "meta" / "episodes.jsonl"
        if episodes_jsonl.exists() and not assume_success:
            for line in episodes_jsonl.read_text().splitlines():
                obj = json.loads(line)
                episodes_meta[obj["episode_index"]] = obj

        for pf in parquet_files:
            table = pq.read_table(pf)
            n = table.num_rows
            C = self.chunk_length
            if n < C + 1:
                continue

            states = np.array(table.column("observation.state").to_pylist(), dtype=np.float32)
            actions = np.array(table.column("action").to_pylist(), dtype=np.float32)
            ep_idx = table.column("episode_index")[0].as_py()

            task_idx = table.column("task_index")[0].as_py() if "task_index" in table.column_names else 0
            task_desc = task_map.get(task_idx, "pick and place the object")

            if "success" in table.column_names and not assume_success:
                ep_success = bool(table.column("success")[0].as_py())
            elif ep_idx in episodes_meta and not assume_success:
                ep_success = episodes_meta[ep_idx].get("success", True)
            else:
                ep_success = True
            ep_reward = 1.0 if ep_success else 0.0

            if "next.done" in table.column_names:
                dones = np.array(table.column("next.done").to_pylist(), dtype=np.float32)
            else:
                dones = np.zeros(n, dtype=np.float32)
                dones[-1] = 1.0

            chunk_idx = ep_idx // 1000
            agentview_frames = self._load_video_frames(
                data_dir / "videos" / f"chunk-{chunk_idx:03d}"
                / "observation.images.agentview" / f"episode_{ep_idx:06d}.mp4"
            )
            wrist_frames = self._load_video_frames(
                data_dir / "videos" / f"chunk-{chunk_idx:03d}"
                / "observation.images.wrist" / f"episode_{ep_idx:06d}.mp4"
            )

            if agentview_frames is None or wrist_frames is None:
                logger.warning(f"Skipping episode {ep_idx}: video not found")
                continue

            agentview_frames = agentview_frames[:n]
            wrist_frames = wrist_frames[:n]
            if len(agentview_frames) < n:
                logger.warning(f"Episode {ep_idx}: video shorter than parquet; skipping")
                continue

            for i in range(n - C):
                j = min(i + C, n - 1)
                self.transitions.append({
                    "image": agentview_frames[i],
                    "wrist_image": wrist_frames[i],
                    "state": states[i],
                    "action_chunk": actions[i : i + C],
                    "reward": np.array([ep_reward], dtype=np.float32),
                    "done": np.array([float(dones[j])], dtype=np.float32),
                    "next_image": agentview_frames[j],
                    "next_wrist_image": wrist_frames[j],
                    "next_state": states[j],
                    "task_description": task_desc,
                })

        logger.info(f"Loaded {len(self.transitions)} transitions (VLAW format)")

    def _load_video_frames(self, video_path: pathlib.Path) -> list[np.ndarray] | None:
        import cv2

        if not video_path.exists():
            return None
        try:
            import imageio
            reader = imageio.get_reader(str(video_path), "ffmpeg")
            frames = []
            for frame in reader:
                frame = np.asarray(frame)
                if frame.shape[:2] != (self.resize_size, self.resize_size):
                    frame = cv2.resize(frame, (self.resize_size, self.resize_size))
                frames.append(frame.astype(np.uint8))
            reader.close()
            return frames
        except Exception as e:
            logger.warning(f"Failed to read video {video_path}: {e}")
            return None

    # ------------------------------------------------------------------ #
    # Perturbed trajectories layout (embedded PNG images in parquet)
    # ------------------------------------------------------------------ #

    def _load_perturbed(self, data_dir: pathlib.Path, assume_success: bool):
        import pyarrow.parquet as pq
        from PIL import Image

        logger.info(f"Detected perturbed-trajectory layout in {data_dir}")

        parquet_dir = data_dir / "data"
        if not parquet_dir.exists():
            parquet_dir = data_dir
        parquet_files = sorted(parquet_dir.rglob("*.parquet"))
        if not parquet_files:
            raise FileNotFoundError(f"No parquet files under {data_dir}")
        logger.info(f"Found {len(parquet_files)} parquet files")

        meta_path = data_dir / "collection_metadata.json"
        episode_success: dict[int, bool] = {}
        episode_task_desc: dict[int, str] = {}
        if meta_path.exists():
            meta = json.loads(meta_path.read_text())
            for ep_info in meta.get("episodes", []):
                eidx = ep_info.get("episode_idx", ep_info.get("episode_index", -1))
                if not assume_success:
                    episode_success[eidx] = ep_info.get("success", True)
                episode_task_desc[eidx] = ep_info.get(
                    "original_instruction", "pick and place the object"
                )

        C = self.chunk_length
        for pf in parquet_files:
            table = pq.read_table(pf)
            n = table.num_rows
            if n < C + 1:
                continue

            states = np.array(table.column("state").to_pylist(), dtype=np.float32)
            actions = np.array(table.column("actions").to_pylist(), dtype=np.float32)
            ep_idx = table.column("episode_index")[0].as_py()
            task_desc = episode_task_desc.get(ep_idx, "pick and place the object")

            ep_reward = 1.0 if assume_success else (
                1.0 if episode_success.get(ep_idx, True) else 0.0
            )

            images = self._decode_image_column(table.column("image"), n)
            wrist_images = self._decode_image_column(table.column("wrist_image"), n)

            for i in range(n - C):
                j = min(i + C, n - 1)
                self.transitions.append({
                    "image": images[i],
                    "wrist_image": wrist_images[i],
                    "state": states[i],
                    "action_chunk": actions[i : i + C],
                    "reward": np.array([ep_reward], dtype=np.float32),
                    "done": np.array([float(i + C >= n - 1)], dtype=np.float32),
                    "next_image": images[j],
                    "next_wrist_image": wrist_images[j],
                    "next_state": states[j],
                    "task_description": task_desc,
                })

        logger.info(f"Loaded {len(self.transitions)} transitions (perturbed format)")

    def _decode_image_column(self, col, n: int) -> list[np.ndarray]:
        from PIL import Image

        images = []
        for row_idx in range(n):
            raw = col[row_idx]
            img_bytes = raw["bytes"].as_py()
            img = Image.open(io.BytesIO(img_bytes)).convert("RGB")
            if img.size != (self.resize_size, self.resize_size):
                img = img.resize((self.resize_size, self.resize_size), Image.BILINEAR)
            images.append(np.asarray(img, dtype=np.uint8))
        return images

    def __len__(self):
        return len(self.transitions)

    def sample(self, batch_size: int) -> dict[str, Any]:
        """Sample a batch. Returns stacked arrays + list of task_descriptions."""
        indices = np.random.randint(0, len(self.transitions), size=batch_size)
        batch: dict[str, list] = collections.defaultdict(list)
        for idx in indices:
            for key, value in self.transitions[idx].items():
                batch[key].append(value)
        out: dict[str, Any] = {}
        for key, values in batch.items():
            if isinstance(values[0], np.ndarray):
                out[key] = np.stack(values)
            else:
                out[key] = values
        return out


# ---------------------------------------------------------------------------
# Target network utilities
# ---------------------------------------------------------------------------

def _copy_params(source_state, target_state):
    source_flat = source_state.flat_state()
    target_flat = target_state.flat_state()
    for key in target_flat:
        if key in source_flat:
            target_flat[key].value = source_flat[key].value
    return target_state


def _soft_update_params(source_state, target_state, tau: float):
    source_flat = source_state.flat_state()
    target_flat = target_state.flat_state()
    for key in target_flat:
        if key in source_flat:
            target_flat[key].value = (
                tau * source_flat[key].value + (1.0 - tau) * target_flat[key].value
            )
    return target_state


# ---------------------------------------------------------------------------
# Observation builder — uses the model's transform pipeline
# ---------------------------------------------------------------------------

def _build_transform_pipeline(full_config, rlt_config, checkpoint_dir):
    """Build the input transform pipeline (same as serve_rlt_policy.py).

    Returns:
        input_transforms: list of transform functions.
        norm_stats: normalisation statistics (for normalising action chunks).
        use_quantiles: whether to use quantile normalisation.
    """
    import openpi.transforms as transforms
    from openpi.training import checkpoints as _checkpoints

    data_config = full_config.data.create(full_config.assets_dirs, rlt_config)
    norm_stats = _checkpoints.load_norm_stats(
        checkpoint_dir / "assets", data_config.asset_id
    )

    input_transforms = [
        *data_config.data_transforms.inputs,
        transforms.Normalize(norm_stats, use_quantiles=data_config.use_quantile_norm),
        *data_config.model_transforms.inputs,
    ]
    return input_transforms, norm_stats, data_config.use_quantile_norm


def _apply_transforms(transforms_list, sample: dict) -> dict:
    for t in transforms_list:
        sample = t(sample)
    return sample


def _prepare_batch(
    batch: dict[str, Any],
    input_transforms: list,
    norm_stats,
    use_quantiles: bool,
    prefix: str = "",
    model_action_dim: int = 32,
) -> dict:
    """Convert a raw batch into a model-ready observation dict.

    Also normalises and pads the action chunks to model_action_dim.
    """
    batch_size = batch[f"{prefix}image"].shape[0]
    task_descs = batch["task_description"]

    obs_batch: dict[str, list] = collections.defaultdict(list)

    for i in range(batch_size):
        sample = {
            "observation/image": batch[f"{prefix}image"][i],
            "observation/wrist_image": batch[f"{prefix}wrist_image"][i],
            "observation/state": batch[f"{prefix}state"][i],
            "prompt": task_descs[i],
        }
        transformed = _apply_transforms(input_transforms, sample)
        for key, val in transformed.items():
            obs_batch[key].append(val)

    stacked: dict[str, Any] = {}
    for key, vals in obs_batch.items():
        if isinstance(vals[0], np.ndarray):
            stacked[key] = np.stack(vals)
        elif isinstance(vals[0], (int, float, bool)):
            stacked[key] = np.array(vals)
        elif isinstance(vals[0], dict):
            stacked[key] = {}
            for subkey in vals[0]:
                stacked[key][subkey] = np.stack([v[subkey] for v in vals])
        else:
            stacked[key] = vals

    # Normalise and pad action_chunk to match model space
    raw_actions = batch["action_chunk"].astype(np.float32)
    if norm_stats is not None and "actions" in norm_stats:
        a_stats = norm_stats["actions"]
        if use_quantiles:
            q01 = a_stats.q01[..., :raw_actions.shape[-1]]
            q99 = a_stats.q99[..., :raw_actions.shape[-1]]
            raw_actions = (raw_actions - q01) / (q99 - q01 + 1e-6) * 2 - 1
        else:
            mean = a_stats.mean[..., :raw_actions.shape[-1]]
            std = a_stats.std[..., :raw_actions.shape[-1]]
            raw_actions = (raw_actions - mean) / (std + 1e-6)

    if raw_actions.shape[-1] < model_action_dim:
        pad_width = model_action_dim - raw_actions.shape[-1]
        raw_actions = np.pad(raw_actions, ((0, 0), (0, 0), (0, pad_width)))
    stacked["_action_chunk_padded"] = raw_actions

    return stacked


# ---------------------------------------------------------------------------
# Phase 1: RL Token encoder-decoder training (on the same offline data)
# ---------------------------------------------------------------------------

def train_rl_token(args: Args, model, dataset, input_transforms, rng):
    """Train RL token encoder-decoder on offline demonstration data.

    L_total = L_reconstruction + alpha * L_vla_flow_matching
    """
    import jax
    import jax.numpy as jnp
    import flax.nnx as nnx
    import optax

    from openpi.models import model as _model

    if args.rl_token_steps <= 0:
        logger.info("Skipping RL Token training (rl_token_steps=0).")
        return model, rng

    logger.info("=" * 60)
    logger.info("Phase 1: RL Token Encoder-Decoder Training")
    logger.info("=" * 60)
    logger.info(f"Steps: {args.rl_token_steps}, batch_size: {args.rl_token_batch_size}")
    logger.info(f"Finetune VLA: {args.finetune_vla} (weight={args.vla_finetune_weight})")

    optimizer = optax.adam(args.rl_token_lr)

    # Collect all trainable params:
    #   - RL encoder + decoder (always trained)
    #   - VLA backbone (optionally fine-tuned)
    if args.finetune_vla:
        train_params = nnx.state(model, nnx.Param)
    else:
        # Only train encoder + decoder params
        train_params = nnx.state(model.rl_encoder, nnx.Param)
        train_params_dec = nnx.state(model.rl_decoder, nnx.Param)

    opt_state = optimizer.init(train_params)

    best_loss = float("inf")
    t0 = time.time()

    for step in range(1, args.rl_token_steps + 1):
        rng, step_rng = jax.random.split(rng)
        batch = dataset.sample(args.rl_token_batch_size)

        # Build observation through transform pipeline (only current obs needed)
        obs_batch: dict[str, list] = collections.defaultdict(list)
        task_descs = batch["task_description"]
        bs = batch["image"].shape[0]
        for i in range(bs):
            sample = {
                "observation/image": batch["image"][i],
                "observation/wrist_image": batch["wrist_image"][i],
                "observation/state": batch["state"][i],
                "prompt": task_descs[i],
            }
            transformed = _apply_transforms(input_transforms, sample)
            for key, val in transformed.items():
                obs_batch[key].append(val)

        stacked: dict[str, Any] = {}
        for key, vals in obs_batch.items():
            if isinstance(vals[0], np.ndarray):
                stacked[key] = np.stack(vals)
            elif isinstance(vals[0], (int, float, bool)):
                stacked[key] = np.array(vals)
            elif isinstance(vals[0], dict):
                stacked[key] = {}
                for subkey in vals[0]:
                    stacked[key][subkey] = np.stack([v[subkey] for v in vals])
            else:
                stacked[key] = vals

        observation = _model.Observation.from_dict(stacked)

        # Compute RL token reconstruction loss
        rl_token_loss = model.compute_rl_token_loss(observation)
        total_loss = rl_token_loss

        if args.finetune_vla and "actions" in stacked:
            actions = jnp.array(stacked["actions"])
            vla_loss = jnp.mean(model.compute_loss(step_rng, observation, actions, train=True))
            total_loss = rl_token_loss + args.vla_finetune_weight * vla_loss

        if step % args.log_interval == 0:
            loss_val = float(total_loss)
            elapsed = time.time() - t0
            logger.info(
                f"[RL Token] Step {step}/{args.rl_token_steps} | "
                f"Loss: {loss_val:.6f} | {step / elapsed:.1f} steps/s"
            )
            if loss_val < best_loss:
                best_loss = loss_val

    # Save RL token checkpoint
    from openpi.training import checkpoints as _checkpoints
    output_dir = pathlib.Path(args.output_dir)
    rl_token_dir = output_dir / "rl_token"
    rl_token_dir.mkdir(parents=True, exist_ok=True)
    _checkpoints.save_state(rl_token_dir, nnx.state(model))
    logger.info(f"RL Token training complete (best loss: {best_loss:.6f}) → {rl_token_dir}")

    return model, rng


# ---------------------------------------------------------------------------
# Phase 2: Offline TD3 Actor-Critic training
# ---------------------------------------------------------------------------

def train_actor_critic(args: Args, model, dataset, input_transforms, norm_stats,
                       use_quantiles, rng):
    """Train Actor and Critic via offline TD3 using the learned z_rl."""
    import jax
    import jax.numpy as jnp
    import flax.nnx as nnx
    import optax

    from openpi.models.pi0_rlt import RLCritic
    from openpi.models import model as _model

    if args.rl_steps <= 0:
        logger.info("Skipping Actor-Critic training (rl_steps=0).")
        return model, rng

    logger.info("=" * 60)
    logger.info("Phase 2: Offline TD3 Actor-Critic Training")
    logger.info("=" * 60)
    logger.info(f"Steps:  {args.rl_steps}, batch_size: {args.rl_batch_size}")
    logger.info(f"Gamma:  {args.discount_gamma}, BC beta: {args.bc_regularizer_beta}")

    model_action_dim = model.action_dim  # 32 for pi05

    # Build target critic
    rng, target_rng = jax.random.split(rng)
    target_critic = RLCritic(
        rl_token_dim=args.rl_token_dim,
        prop_state_dim=model_action_dim,
        action_dim=model_action_dim,
        chunk_length=args.rl_chunk_length,
        hidden_dim=args.critic_hidden_dim,
        num_layers=args.critic_num_layers,
        rngs=nnx.Rngs(target_rng),
    )
    target_critic_state = nnx.state(target_critic)
    _copy_params(nnx.state(model.rl_critic), target_critic_state)
    nnx.update(target_critic, target_critic_state)
    logger.info("Target critic initialised.")

    # Optimizers (actor + critic only)
    actor_optimizer = optax.adam(args.actor_lr)
    critic_optimizer = optax.adam(args.critic_lr)
    actor_opt_state = actor_optimizer.init(nnx.state(model.rl_actor, nnx.Param))
    critic_opt_state = critic_optimizer.init(nnx.state(model.rl_critic, nnx.Param))

    # Optional VLA fine-tuning during Phase 2
    finetune_vla_p2 = args.finetune_vla_phase2
    if finetune_vla_p2:
        vla_optimizer = optax.adam(args.vla_lr_phase2)
        vla_train_params = nnx.state(model, nnx.Param)
        vla_opt_state = vla_optimizer.init(vla_train_params)
        logger.info(
            f"VLA fine-tuning enabled in Phase 2 "
            f"(lr={args.vla_lr_phase2}, weight={args.vla_phase2_weight}, "
            f"interval={args.vla_phase2_interval})"
        )

    gamma_C = args.discount_gamma ** args.rl_chunk_length

    def _extract_features(prepared_batch: dict, rng_key):
        observation = _model.Observation.from_dict(prepared_batch)
        rl_token = model.extract_rl_token(observation)
        ref_actions = model.sample_vla_reference(
            rng_key, observation, num_steps=args.vla_num_steps
        )
        ref_chunk = ref_actions[:, :args.rl_chunk_length, :]
        return rl_token, ref_chunk, observation.state

    @jax.jit
    def critic_step(critic_params, critic_opt_state, rl_token, prop_state,
                    action_chunk, reward, done, next_rl_token, next_prop_state,
                    next_ref_chunk, rng_key):
        def critic_loss_fn(c_params):
            nnx.update(model.rl_critic, c_params)
            q1, q2 = model.rl_critic(rl_token, prop_state, action_chunk)
            next_action = model.rl_actor.sample(
                rng_key, next_rl_token, next_prop_state, next_ref_chunk
            )
            next_q = jax.lax.stop_gradient(
                target_critic.q_min(next_rl_token, next_prop_state, next_action)
            )
            q_target = reward + gamma_C * (1.0 - done) * next_q
            q_target = jax.lax.stop_gradient(q_target)
            return jnp.mean(jnp.square(q1 - q_target) + jnp.square(q2 - q_target))

        loss, grads = jax.value_and_grad(critic_loss_fn)(critic_params)
        updates, new_opt = critic_optimizer.update(grads, critic_opt_state, critic_params)
        new_params = optax.apply_updates(critic_params, updates)
        return new_params, new_opt, loss

    @jax.jit
    def actor_step(actor_params, actor_opt_state, rl_token, prop_state,
                   ref_chunk, rng_key):
        beta = args.bc_regularizer_beta

        def actor_loss_fn(a_params):
            nnx.update(model.rl_actor, a_params)
            action = model.rl_actor.sample(rng_key, rl_token, prop_state, ref_chunk)
            q_value = model.rl_critic.q_min(rl_token, prop_state, action)
            bc_reg = jnp.mean(jnp.sum(jnp.square(action - ref_chunk), axis=(-2, -1)))
            return -jnp.mean(q_value) + beta * bc_reg

        loss, grads = jax.value_and_grad(actor_loss_fn)(actor_params)
        updates, new_opt = actor_optimizer.update(grads, actor_opt_state, actor_params)
        new_params = optax.apply_updates(actor_params, updates)
        return new_params, new_opt, loss

    # Training loop
    output_dir = pathlib.Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    np.random.seed(args.seed + 1)
    total_critic_loss = 0.0
    total_actor_loss = 0.0
    total_vla_loss = 0.0
    vla_update_count = 0
    t0 = time.time()

    logger.info(f"Starting offline TD3 for {args.rl_steps} steps...")

    for step in range(1, args.rl_steps + 1):
        rng, step_rng = jax.random.split(rng)

        batch = dataset.sample(args.rl_batch_size)

        cur_prepared = _prepare_batch(
            batch, input_transforms, norm_stats, use_quantiles,
            prefix="", model_action_dim=model_action_dim,
        )
        next_prepared = _prepare_batch(
            batch, input_transforms, norm_stats, use_quantiles,
            prefix="next_", model_action_dim=model_action_dim,
        )

        rng, rng_cur, rng_next = jax.random.split(rng, 3)
        rl_token, ref_chunk, prop_state = _extract_features(cur_prepared, rng_cur)
        next_rl_token, next_ref_chunk, next_prop_state = _extract_features(
            next_prepared, rng_next
        )

        action_chunk = jnp.array(cur_prepared["_action_chunk_padded"])
        reward = jnp.array(batch["reward"])
        done = jnp.array(batch["done"])

        # Critic update
        rng, critic_rng = jax.random.split(rng)
        critic_params = nnx.state(model.rl_critic, nnx.Param)
        critic_params, critic_opt_state, c_loss = critic_step(
            critic_params, critic_opt_state,
            rl_token, prop_state, action_chunk, reward, done,
            next_rl_token, next_prop_state, next_ref_chunk, critic_rng,
        )
        nnx.update(model.rl_critic, critic_params)
        total_critic_loss += float(c_loss)

        # Actor update (delayed)
        if step % args.critic_updates_per_actor == 0:
            rng, actor_rng = jax.random.split(rng)
            actor_params = nnx.state(model.rl_actor, nnx.Param)
            actor_params, actor_opt_state, a_loss = actor_step(
                actor_params, actor_opt_state,
                rl_token, prop_state, ref_chunk, actor_rng,
            )
            nnx.update(model.rl_actor, actor_params)
            total_actor_loss += float(a_loss)

            # Soft-update target critic
            _soft_update_params(
                nnx.state(model.rl_critic),
                nnx.state(target_critic),
                args.target_network_tau,
            )
            nnx.update(target_critic, nnx.state(target_critic))

        # VLA fine-tuning step (supervised flow matching loss on offline data)
        if finetune_vla_p2 and step % args.vla_phase2_interval == 0:
            rng, vla_rng = jax.random.split(rng)
            vla_batch = dataset.sample(args.rl_token_batch_size)

            # Build observation through transform pipeline
            vla_obs_batch: dict[str, list] = collections.defaultdict(list)
            vla_bs = vla_batch["image"].shape[0]
            for i in range(vla_bs):
                sample = {
                    "observation/image": vla_batch["image"][i],
                    "observation/wrist_image": vla_batch["wrist_image"][i],
                    "observation/state": vla_batch["state"][i],
                    "prompt": vla_batch["task_description"][i],
                }
                transformed = _apply_transforms(input_transforms, sample)
                for key, val in transformed.items():
                    vla_obs_batch[key].append(val)

            vla_stacked: dict[str, Any] = {}
            for key, vals in vla_obs_batch.items():
                if isinstance(vals[0], np.ndarray):
                    vla_stacked[key] = np.stack(vals)
                elif isinstance(vals[0], (int, float, bool)):
                    vla_stacked[key] = np.array(vals)
                elif isinstance(vals[0], dict):
                    vla_stacked[key] = {}
                    for subkey in vals[0]:
                        vla_stacked[key][subkey] = np.stack([v[subkey] for v in vals])
                else:
                    vla_stacked[key] = vals

            if "actions" in vla_stacked:
                vla_observation = _model.Observation.from_dict(vla_stacked)
                vla_actions = jnp.array(vla_stacked["actions"])

                def vla_loss_fn(params):
                    nnx.update(model, params)
                    return jnp.mean(model.compute_loss(vla_rng, vla_observation, vla_actions, train=True))

                vla_params = nnx.state(model, nnx.Param)
                vla_loss_val, vla_grads = jax.value_and_grad(vla_loss_fn)(vla_params)
                vla_updates, vla_opt_state = vla_optimizer.update(vla_grads, vla_opt_state, vla_params)
                vla_new_params = optax.apply_updates(vla_params, vla_updates)
                nnx.update(model, vla_new_params)
                total_vla_loss += float(vla_loss_val)
                vla_update_count += 1

        # Logging
        if step % args.log_interval == 0:
            avg_c = total_critic_loss / step
            actor_updates = step // args.critic_updates_per_actor
            avg_a = total_actor_loss / max(actor_updates, 1)
            elapsed = time.time() - t0
            vla_str = ""
            if finetune_vla_p2 and vla_update_count > 0:
                avg_vla = total_vla_loss / vla_update_count
                vla_str = f" | VLA: {avg_vla:.6f}"
            logger.info(
                f"[TD3] Step {step}/{args.rl_steps} | "
                f"Critic: {avg_c:.6f} | Actor: {avg_a:.6f}{vla_str} | "
                f"{step / elapsed:.1f} steps/s"
            )

        # Checkpointing
        if step % args.save_interval == 0:
            ckpt_dir = output_dir / "td3" / f"step_{step:06d}"
            ckpt_dir.mkdir(parents=True, exist_ok=True)
            from openpi.training import checkpoints as _checkpoints
            if finetune_vla_p2:
                _checkpoints.save_state(ckpt_dir / "full_model", nnx.state(model))
            else:
                _checkpoints.save_state(ckpt_dir / "actor", nnx.state(model.rl_actor))
                _checkpoints.save_state(ckpt_dir / "critic", nnx.state(model.rl_critic))
            _checkpoints.save_state(ckpt_dir / "target_critic", nnx.state(target_critic))
            with open(ckpt_dir / "training_state.json", "w") as f:
                json.dump({
                    "step": step,
                    "avg_critic_loss": total_critic_loss / step,
                    "avg_actor_loss": total_actor_loss / max(actor_updates, 1),
                }, f, indent=2)
            logger.info(f"Checkpoint → {ckpt_dir}")

    # Final save — full model
    from openpi.training import checkpoints as _checkpoints
    final_dir = output_dir / "best"
    final_dir.mkdir(parents=True, exist_ok=True)
    _checkpoints.save_state(final_dir, nnx.state(model))
    with open(final_dir / "training_state.json", "w") as f:
        json.dump({
            "step": args.rl_steps,
            "avg_critic_loss": total_critic_loss / max(args.rl_steps, 1),
            "avg_actor_loss": total_actor_loss / max(
                args.rl_steps // args.critic_updates_per_actor, 1
            ),
        }, f, indent=2)

    logger.info(f"TD3 training complete → {final_dir}")
    return model, rng


def main(args: Args):
    import jax
    import jax.numpy as jnp
    import flax.nnx as nnx

    from openpi.models.pi0_rlt import Pi0RLTConfig
    from openpi.training import config as _config
    from openpi.models import model as _model

    logger.info("=" * 60)
    logger.info("Fully-Offline RLT Training")
    logger.info("=" * 60)
    logger.info(f"Data:   {args.data_dir}")
    logger.info(f"Output: {args.output_dir}")

    full_config = _config.get_config(args.base_config)
    model_kwargs = dataclasses.asdict(full_config.model)
    rlt_config = Pi0RLTConfig(
        **model_kwargs,
        rl_token_dim=args.rl_token_dim,
        encoder_num_layers=args.encoder_num_layers,
        decoder_num_layers=args.decoder_num_layers,
        actor_hidden_dim=args.actor_hidden_dim,
        actor_num_layers=args.actor_num_layers,
        critic_hidden_dim=args.critic_hidden_dim,
        critic_num_layers=args.critic_num_layers,
        rl_chunk_length=args.rl_chunk_length,
        actor_std=args.actor_std,
        ref_action_dropout=args.ref_action_dropout,
        bc_regularizer_beta=args.bc_regularizer_beta,
        discount_gamma=args.discount_gamma,
        vla_num_steps=args.vla_num_steps,
    )

    rng = jax.random.key(args.seed)
    rng, model_rng = jax.random.split(rng)
    logger.info("Creating Pi0RLT model...")
    model = rlt_config.create(model_rng)

    logger.info(f"Loading VLA weights from {args.base_checkpoint}...")
    checkpoint_dir = pathlib.Path(args.base_checkpoint)
    if str(checkpoint_dir).startswith("gs://"):
        import openpi.shared.download as download
        checkpoint_dir = pathlib.Path(download.maybe_download(str(checkpoint_dir)))

    vla_params = _model.restore_params(checkpoint_dir / "params", dtype=jnp.bfloat16)

    from orbax import checkpoint as ocp
    graphdef, state = nnx.split(model)
    vla_intersect = ocp.transform_utils.intersect_trees(state.to_pure_dict(), vla_params)
    state.replace_by_pure_dict(vla_intersect)
    model = nnx.merge(graphdef, state)
    logger.info("VLA weights loaded.")

    full_config_with_rlt = dataclasses.replace(full_config, model=rlt_config)
    input_transforms, norm_stats, use_quantiles = _build_transform_pipeline(
        full_config_with_rlt, rlt_config, checkpoint_dir
    )
    logger.info(f"Transforms: {[type(t).__name__ for t in input_transforms]}")
    logger.info(f"Loading offline data from {args.data_dir}...")
    dataset = OfflineDataset(
        data_dir=args.data_dir,
        chunk_length=args.rl_chunk_length,
        assume_success=args.assume_success,
        resize_size=args.resize_size,
    )
    min_bs = max(args.rl_token_batch_size, args.rl_batch_size)
    if len(dataset) < min_bs:
        raise ValueError(
            f"Dataset has {len(dataset)} transitions, need >= {min_bs}"
        )

    model, rng = train_rl_token(args, model, dataset, input_transforms, rng)
    model, rng = train_actor_critic(
        args, model, dataset, input_transforms, norm_stats, use_quantiles, rng
    )

    logger.info("All done.")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, force=True)
    main(tyro.cli(Args))
